name: Build and Upload APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el SDK de Android
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.2
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      # 2. Configura el JDK de Java
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Revisa el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 4. Da permisos de ejecución al script gradlew
      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      # 5. Configura Gradle para firmar el APK con el Keystore generado
      - name: Build APK
        run: ./gradlew assembleRelease

      # 6. Subir el APK generado a GitHub Artifacts
      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/*/*.apk
