name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/dl/android/studio/ide-zips/2023.2.1.21/android-studio-2023.2.1.21-linux.tar.gz
        tar -xvzf android-studio-2023.2.1.21-linux.tar.gz
        sudo mv android-studio /opt/
        export ANDROID_HOME=/opt/android-studio
        export PATH=$PATH:$ANDROID_HOME/bin
        sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools" "tools"
        sdkmanager --update

    - name: Create Android Project
      run: |
        # Crear un nuevo proyecto con el nombre Generador
        ./gradlew createProject \
        -Pname="Generador" \
        -Ppackage="com.android.generador" \
        -Planguage=kotlin

    - name: Build the app
      run: |
        ./gradlew build

    - name: Run tests
      run: |
        ./gradlew test
