name: Build Android Project with Kotlin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'  # Especificamos la distribución

    - name: Install Android Command Line Tools
      run: |
        # Crear el directorio para el SDK de Android
        mkdir -p $HOME/android-sdk-linux
        cd $HOME/android-sdk-linux
        # Descargar las herramientas de línea de comandos de Android
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip
        rm commandlinetools-linux-8512546_latest.zip
        
        # Establecer las variables de entorno para el SDK
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk-linux" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
        
        # Verificar que sdkmanager esté accesible
        echo "Verificando sdkmanager"
        sdkmanager --version

    - name: Install SDK Packages
      run: |
        # Aceptar todas las licencias y instalar los paquetes necesarios
        sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

    - name: Create Android Project
      run: |
        # Crear el proyecto
        cd $GITHUB_WORKSPACE
        echo "Creating Android project..."
        mkdir Generador
        cd Generador
        # Inicializar el proyecto con Gradle y Kotlin
        gradle init --type kotlin-library
        
        # Crear el archivo Kotlin
        mkdir -p src/main/kotlin/com/android/generador
        echo "package com.android.generador" > src/main/kotlin/com/android/generador/Generador.kt

    - name: Build the Project
      run: |
        cd $GITHUB_WORKSPACE/Generador
        ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: $GITHUB_WORKSPACE/Generador/build/outputs/
