name: Android Build

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama en la que trabajas si es diferente
  pull_request:
    branches:
      - main  # Cambia 'main' por la rama en la que trabajas si es diferente

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos la última versión de Ubuntu como entorno de ejecución
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clona el repositorio
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Android requiere Java 11, pero si necesitas otro JDK, cámbialo
        distribution: 'adoptopenjdk'
    
    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-manager-action@v3
      with:
        api-levels: '30'  # Cambia esto al nivel de API que estés utilizando
        build-tools: '30.0.3'  # Cambia a la versión de build-tools que estés utilizando
    
    - name: Build Release APK
      run: ./gradlew assembleRelease  # Para compilar el APK de release, puedes cambiar a assembleDebug si necesitas el APK de debug

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Cambia según la ruta de salida de tu APK
